on:
  push:
    tags:
      - v*
name: make-release
jobs:
  makerelease:
    name: make release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.x'
      - name: Run make generate
        run: |
          make generate
        shell: bash
      # Ensure no files changed.
      - name: Ensure no files changed
        shell: bash
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "Files changed, exiting";
            exit 1;
          else
            # No changes
            echo "No files changed, proceeding";
          fi
      - name: Create a Release
        uses: softprops/action-gh-release@v1
